[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM9
lib_ldf_mode = deep
lib_deps =
    WiFi
    WiFiClientSecure
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    knolleary/PubSubClient @ ^2.8
